#! /bin/sh

rm cmake_install.cmake
rm CMakeLists.txt.user
rm  Makefile
rm CMakeCache.txt
rm -rf CMakeFiles/

rm -r build
rm -r `find examples/ -name build`
rm -r external/Gamma/build
rm -r external/glew/build/build
rm -r external/glfw/build
