name: CMake

on:
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential xorg-dev git git-lfs cmake \
          libsndfile1-dev libassimp-dev libasound2-dev libxrandr-dev \
          libopengl-dev libxinerama-dev libxcursor-dev libxi-dev \
          libgl1-mesa-dev libglu1-mesa-dev

    - name: Update submodules
      run: git submodule update --init --recursive --depth=10

    - name: Configure CMake
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DALLOLIB_BUILD_EXAMPLES=ON
        -DALLOLIB_BUILD_TESTS=ON
        -DCMAKE_POLICY_VERSION_MINIMUM=3.5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 2

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
